<img src="files/numpy.jpg">

* Librairie Python dédiée aux tableaux multidimensionnels et aux matrices</li>
* Contient aussi des fonctions mathématiques à appliquer à ces tableaux
* Souvent couplée à SciPy et Matplotlib
    * SciPy propose d'autres fonctions mathématiques
    * Matplotlib est une librairie pour les représentations graphiques
* Le trio NumPy/SciPy/Matplotlib constitue une alternative libre à Matlab

* Convention: import numpy as np
* L'objet array est le point central de NumPy
* Dans un array tous les éléments doivent être de même type
* La taille du tableau doit être fixée à la création de l'objet array
* Pas de limite sur le nombre de dimensions du tableau (sauf capacité du programmeur)

In [60]:
import numpy as np

# Création et manipulation de tableaux et matrices (array)

### Création d'un tableau à partir d'une liste ou d'un tuple

In [61]:
np.array([1,2,3,4])

array([1, 2, 3, 4])

In [62]:
np.array((1,2,3,4))

array([1, 2, 3, 4])

In [63]:
np.array([[1, 2], [3, 4]])

array([[1, 2],
       [3, 4]])

In [64]:
np.array([[[1,2], [3,4]], [[4,5], [6,7]]])

array([[[1, 2],
        [3, 4]],

       [[4, 5],
        [6, 7]]])

### Création d'un tableau directement avec numpy

In [65]:
np.arange(100, 130, 2)

array([100, 102, 104, 106, 108, 110, 112, 114, 116, 118, 120, 122, 124,
       126, 128])

In [66]:
np.linspace(0, 1, 5)

array([ 0.  ,  0.25,  0.5 ,  0.75,  1.  ])

### Type du tableau

Python devinne le type du tableau, mais il est possible de le préciser

In [67]:
np.array([[1,2], [3,4]], int)

array([[1, 2],
       [3, 4]])

In [68]:
np.array([[1,2], [3,4]], float)

array([[ 1.,  2.],
       [ 3.,  4.]])

In [69]:
np.arange(10, dtype=int)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [70]:
np.arange(10, dtype=float)

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9.])

### Dimensions du tableau

* ndim donne le nombre de dimensions du tableau
* shape donne les dimensions

In [71]:
A = np.array([[[1,2], [3,4]], [[4,5], [6,7]]])
print("A = \n{} \n\nNombre dimensions: {}, Dimensions: {}".format(
        A, np.ndim(A), np.shape(A)))

A = 
[[[1 2]
  [3 4]]

 [[4 5]
  [6 7]]] 

Nombre dimensions: 3, Dimensions: (2, 2, 2)


### Affichage d'éléments du tableau

Fonctionne comme les list

In [72]:
A[0]

array([[1, 2],
       [3, 4]])

In [73]:
A[0][1]

array([3, 4])

In [74]:
A[-1][-1]

array([6, 7])

### Applatir et re-dimensionner un tableau

In [75]:
A.flatten()

array([1, 2, 3, 4, 4, 5, 6, 7])

In [76]:
B = np.array(range(24))
B

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [77]:
B.reshape(6,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [78]:
B.reshape(2, 4, 3)

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11]],

       [[12, 13, 14],
        [15, 16, 17],
        [18, 19, 20],
        [21, 22, 23]]])

### Concaténation de deux tableaux

Il faut que les deux arrays aient le même nombre de dimensions.  
Fonction: np.concatenate(tuple). Renvoie un nouvel array.  
*Par défaut la concaténation se fait par rapport à la première dimension (axe 0).*

In [79]:
A = np.arange(12).reshape(2, 2, 3)
B = np.arange(100, 112).reshape(2, 2, 3)
result_concat = np.concatenate((A, B))
result_concat

array([[[  0,   1,   2],
        [  3,   4,   5]],

       [[  6,   7,   8],
        [  9,  10,  11]],

       [[100, 101, 102],
        [103, 104, 105]],

       [[106, 107, 108],
        [109, 110, 111]]])

In [80]:
np.shape(result_concat)

(4, 2, 3)

Cette fois on concatène par rapport à la seconde dimension, c'est à dire l'axe 1

In [81]:
result_concat2 = np.concatenate((A, B), axis=1)
result_concat2

array([[[  0,   1,   2],
        [  3,   4,   5],
        [100, 101, 102],
        [103, 104, 105]],

       [[  6,   7,   8],
        [  9,  10,  11],
        [106, 107, 108],
        [109, 110, 111]]])

In [82]:
np.shape(result_concat2)

(2, 4, 3)

### Ajout d'une nouvelle dimension

In [83]:
A = np.arange(6)
A

array([0, 1, 2, 3, 4, 5])

In [84]:
np.shape(A)

(6,)

In [85]:
B = A[:, np.newaxis]
B

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5]])

In [86]:
np.shape(B)

(6, 1)

In [87]:
C = B[:, np.newaxis]
C

array([[[0]],

       [[1]],

       [[2]],

       [[3]],

       [[4]],

       [[5]]])

In [88]:
np.shape(C)

(6, 1, 1)

In [89]:
C.reshape(2,3)

array([[0, 1, 2],
       [3, 4, 5]])

### Création de tableaux avec que des 0 ou que des 1 ou des 1 sur la diagonale

np.zeros(tuple_dimensions) et np.ones(tuple_dimensions)  
Par défaut création d'un array de type float  
Passé en argument le type si int souhaité

In [90]:
np.zeros((2, 4))

array([[ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.]])

In [91]:
np.zeros((2,4), int)

array([[0, 0, 0, 0],
       [0, 0, 0, 0]])

In [92]:
np.ones((2,4))

array([[ 1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.]])

In [93]:
np.eye(3, 3, dtype=int)

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [94]:
np.identity(3)

array([[ 1.,  0.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  0.,  1.]])

In [95]:
vec = np.arange(1, 5)
np.diag(vec)

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

# Opérations sur les tableaux et les matrices

### Opérateurs standards

In [96]:
A = np.arange(10)
B = np.arange(10,20)
print("A = \n{} \n\nB = \n{} \n\nA+B = \n{}".format(A, B, A+B))

A = 
[0 1 2 3 4 5 6 7 8 9] 

B = 
[10 11 12 13 14 15 16 17 18 19] 

A+B = 
[10 12 14 16 18 20 22 24 26 28]


In [97]:
print("AxB = \n{}".format(A*B))

AxB = 
[  0  11  24  39  56  75  96 119 144 171]


In [98]:
A = A.reshape(5,2)
B = B.reshape(5,2)
print("A = \n{} \n\nB = \n{} \n\nA+B = \n{}".format(A, B, A+B))

A = 
[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]] 

B = 
[[10 11]
 [12 13]
 [14 15]
 [16 17]
 [18 19]] 

A+B = 
[[10 12]
 [14 16]
 [18 20]
 [22 24]
 [26 28]]


### Produit matriciel

Soit les deux matrices A et B suivantes  
*Une matrice est un tableau à deux dimensions*

In [99]:
A = np.array([[1,1], [2,3], [1,-1]])
B = np.array([[0,1,-1,-2], [-3,-2,0,1]])
print("A = \n{}\n\nB = \n{}".format(A, B))

A = 
[[ 1  1]
 [ 2  3]
 [ 1 -1]]

B = 
[[ 0  1 -1 -2]
 [-3 -2  0  1]]


*Rappel*  
Pour pouvoir faire un produit de deux matrices il faut que le nombre de colonnes dans la matrice de gauche soit égal au nombre de lignes de la matrice de droite

In [100]:
np.dot(A, B)

array([[-3, -1, -1, -1],
       [-9, -4, -2, -1],
       [ 3,  3, -1, -3]])

### Transposée ($^tA$)

In [101]:
np.transpose(A)

array([[ 1,  2,  1],
       [ 1,  3, -1]])

*Rappel*  
la transposée du produit de A par B, i.e. ($^t(AB)$) est égal au produit de la transposée de B par la transposée de A, i.e. $^tB\: ^tA$

In [102]:
print("t(AB) = \n{}\n\n(tB)(tA) = \n{}".format(np.transpose(np.dot(A, B)), np.dot(np.transpose(B), np.transpose(A))))

t(AB) = 
[[-3 -9  3]
 [-1 -4  3]
 [-1 -2 -1]
 [-1 -1 -3]]

(tB)(tA) = 
[[-3 -9  3]
 [-1 -4  3]
 [-1 -2 -1]
 [-1 -1 -3]]


*Rappel*  
Le produit d'une matrice par sa transposée est toujours défini, il donne une matrice carrée symétrique  
Une matrice est carrée si elle a le même nombre de lignes que de colonnes  
Une matrice A est symétrique lorsque sa tranposée est égale à elle même

In [103]:
print("(A.tA) = \n{}".format(np.dot(A, np.transpose(A))))

(A.tA) = 
[[ 2  5  0]
 [ 5 13 -1]
 [ 0 -1  2]]


### Matrice inverse ($A^{-1}$)

Soit la matrice A suivante

In [104]:
A = np.array([[1,0,-1], [1,-1,0], [1,-1,1]])
print("A = \n{}".format(A))

A = 
[[ 1  0 -1]
 [ 1 -1  0]
 [ 1 -1  1]]


*Rappel*  
Une matrice A est inversible s'il existe une matrice carrée notée $A^{-1}$ telle que $AA^{-1} = A^{-1}A = I_n$ où $I_n$ est une matrice identité

In [105]:
i_A = np.linalg.inv(A)
print(i_A)

[[ 1. -1.  1.]
 [ 1. -2.  1.]
 [ 0. -1.  1.]]


On vérifie les propriétés de $A^{-1}$

In [106]:
print("(Ai_A) = \n{}\n\n(i_AA) = \n{}".format(np.dot(A, i_A), np.dot(i_A, A)))

(Ai_A) = 
[[ 1.  0.  0.]
 [ 0.  1.  0.]
 [ 0.  0.  1.]]

(i_AA) = 
[[ 1.  0.  0.]
 [ 0.  1.  0.]
 [ 0.  0.  1.]]


### Déterminant

*Rappel*  
Une matrice carrée est inversible si et seulement si son déterminant est différent de 0

In [107]:
np.linalg.det(A)

-1.0

## Algèbre linéaire

#### Résolution de système linéaire

In [108]:
A = np.array([[2, 4], [7, 8]])
b = np.array([20, 52])
print("A:\n {}\n\nB:\n{}".format(A, b))

A:
 [[2 4]
 [7 8]]

B:
[20 52]


In [109]:
np.linalg.solve(A, b)

array([ 4.,  3.])

# Sources

* http://math.mad.free.fr/depot/numpy/base.html
* http://wiki.scipy.org/Tentative_NumPy_Tutorial
* http://python.physique.free.fr/outils_math.html
* http://www-irma.u-strasbg.fr/~navaro/imfs/numpy.pdf